<?php
function alnuur_get_pest_services() {
    return [
        'cockroach' => [
            'name' => 'Cockroach Control',
            'slug' => 'cockroach-control',
            'icon' => '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="3"/><path d="M5 7c.5 3 1.5 5 7 5s6.5-2 7-5"/><path d="M5 17c.5-3 1.5-5 7-5s6.5 2 7 5"/><line x1="12" y1="15" x2="12" y2="19"/></svg>',
            'price' => 3500,
            'image' => 'IMAGES/Cockroach Control.jpg',
            'images' => ['IMAGES/Cockroach Control 1.jpg', 'IMAGES/Cockroach Control 2.jpg', 'IMAGES/Cockroach Control.jpg'],
            'desc' => 'Eliminate cockroach infestations with our professional treatment. Safe for families and pets.',
            'features' => ['Gel bait application', 'Residual spray treatment', 'Crack & crevice treatment', 'Preventive measures', '3-month warranty'],
            'featured' => true,
        ],
        'bedbug' => [
            'name' => 'Bed Bug Treatment',
            'slug' => 'bed-bug-treatment',
            'icon' => '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="12" width="20" height="8" rx="2"/><path d="M6 12V8c0-1 .8-2 2-2h3"/><circle cx="8" cy="16" r="1"/><circle cx="16" cy="16" r="1"/></svg>',
            'price' => 5000,
            'image' => 'IMAGES/Bed Bug Treatment.jpg',
            'images' => ['IMAGES/Bed Bug Treatment 1.jpg', 'IMAGES/Bed Bug Treatment 2.jpg', 'IMAGES/Bed Bug Treatment 3.jpg', 'IMAGES/Bed Bug Treatment 4.jpg'],
            'desc' => 'Comprehensive bed bug elimination using heat treatment and approved chemicals.',
            'features' => ['Heat treatment', 'Chemical application', 'Mattress treatment', 'Furniture treatment', 'Follow-up inspection'],
            'featured' => true,
        ],
        'mosquito' => [
            'name' => 'Mosquito Control',
            'slug' => 'mosquito-control',
            'icon' => '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 2v4"/><path d="M10 6h4"/><circle cx="12" cy="12" r="4"/><path d="M6 12H2"/><path d="M22 12h-4"/><path d="M12 16v4"/><path d="M9 19l-2 3"/><path d="M15 19l2 3"/></svg>',
            'price' => 3000,
            'image' => 'IMAGES/Mosquito Control.jpg',
            'images' => ['IMAGES/Mosquito Control 1.jpg', 'IMAGES/Mosquito Control 2.jpg', 'IMAGES/Mosquito Control 3.jpg', 'IMAGES/Mosquito Control.jpg'],
            'desc' => 'Reduce mosquito populations around your property with our effective control program.',
            'features' => ['Larvicide treatment', 'Adulticide fogging', 'Breeding site elimination', 'Residual barrier spray', 'Monthly maintenance'],
            'featured' => true,
        ],
        'rat' => [
            'name' => 'Rat Control',
            'slug' => 'rat-control',
            'icon' => '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="9" cy="15" r="5"/><path d="M14 15c3 0 5-1 5-4V5"/><line x1="17" y1="8" x2="19" y2="8"/><line x1="7" y1="13" x2="7" y2="11"/><line x1="11" y1="13" x2="11" y2="11"/></svg>',
            'price' => 4000,
            'image' => 'IMAGES/Rat Control.jpg',
            'images' => ['IMAGES/Rat Control 1.jpg', 'IMAGES/Rat Control.jpg', 'IMAGES/Rat and pest Control.jpg'],
            'desc' => 'Professional rodent control to eliminate rats and mice from your premises.',
            'features' => ['Rodent baiting', 'Snap traps', 'Exclusion sealing', 'Dropping cleanup', 'Ongoing monitoring'],
            'featured' => true,
        ],
        'termite' => [
            'name' => 'Termite Treatment',
            'slug' => 'termite-treatment',
            'icon' => '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="4" y="8" width="16" height="12" rx="2"/><line x1="8" y1="8" x2="8" y2="4"/><line x1="12" y1="8" x2="12" y2="2"/><line x1="16" y1="8" x2="16" y2="4"/><line x1="8" y1="14" x2="8" y2="18"/><line x1="12" y1="13" x2="12" y2="17"/><line x1="16" y1="14" x2="16" y2="18"/></svg>',
            'price' => 8000,
            'image' => 'IMAGES/Pest Control.jpg',
            'images' => ['IMAGES/Pest Control.jpg', 'IMAGES/Residential & Commercial Pest Control.jpg'],
            'desc' => 'Protect your property from termite damage with our advanced treatment solutions.',
            'features' => ['Soil treatment', 'Wood treatment', 'Baiting system', 'Barrier installation', 'Annual inspections'],
            'featured' => true,
        ],
        'fumigation' => [
            'name' => 'Fumigation Services',
            'slug' => 'fumigation',
            'icon' => '<svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M12 8c0-2 1-4 3-4 2 0 3 2 3 4 0 3-2 5-2 7"/><path d="M6 12c0-2 1-4 3-4s3 2 3 4c0 3-2 5-2 7"/><circle cx="12" cy="18" r="2"/><path d="M3 14c0 0 3-2 9-2s9 2 9 2"/></svg>',
            'price' => 15000,
            'image' => 'IMAGES/Residential & Commercial Pest Control.jpg',
            'images' => ['IMAGES/Residential & Commercial Pest Control 1.jpg', 'IMAGES/Residential & Commercial Pest Control 2.jpg', 'IMAGES/Residential & Commercial Pest Control 4.jpg', 'IMAGES/Residential & Commercial Pest Control 5.jpg'],
            'desc' => 'Complete fumigation for severe infestations. Suitable for residential and commercial properties.',
            'features' => ['Tent fumigation', 'Gas treatment', 'Pre-fumigation inspection', 'Post-fumigation clearance', 'Full property coverage'],
            'featured' => true,
        ],
    ];
}
